// 由 DAZED_COMMANDS_手冊.md 第 4.1 節自動產生，勿手動編輯
namespace HtF.DazedTools.UI
{
    internal static partial class GameData
    {
        // id, /spawn 名稱, 顯示名稱, 類型
        internal static readonly ItemEntry[] Items = new ItemEntry[]
        {
            new ItemEntry(0, "angelfish", "Angelfish", "魚"),
            new ItemEntry(1, "anglerfish", "Anglerfish", "攻擊性魚"),
            new ItemEntry(2, "bass", "Bass", "魚"),
            new ItemEntry(3, "blobfish", "Blobfish", "攻擊性魚"),
            new ItemEntry(4, "bluegill", "Bluegill", "魚"),
            new ItemEntry(5, "albatross", "Albatross", "信天翁"),
            new ItemEntry(6, "blueshark", "Blue Shark", "攻擊性魚"),
            new ItemEntry(7, "bowheadwhale", "Bowhead Whale", "弓頭鯨"),
            new ItemEntry(8, "theoldpike", "The Old Pike", "攻擊性魚"),
            new ItemEntry(9, "giantpiranha", "Giant Piranha", "食人魚"),
            new ItemEntry(10, "goblinshark", "Goblin Shark", "攻擊性魚"),
            new ItemEntry(11, "mutatedbowheadwhale", "Mutated Bowhead Whale", "弓頭鯨"),
            new ItemEntry(12, "pufferfish", "Pufferfish", "河豚"),
            new ItemEntry(13, "spidercrab", "Spidercrab", "蜘蛛蟹"),
            new ItemEntry(14, "sunfish", "Sunfish", "魚"),
            new ItemEntry(15, "tuna", "Tuna", "攻擊性魚"),
            new ItemEntry(16, "bowlfish", "Bowlfish", "魚"),
            new ItemEntry(17, "catfish", "Catfish", "魚"),
            new ItemEntry(18, "clam", "Clam", "生物"),
            new ItemEntry(19, "clownfish", "Clownfish", "魚"),
            new ItemEntry(20, "cod", "Cod", "魚"),
            new ItemEntry(21, "browncrab", "BrownCrab", "螃蟹"),
            new ItemEntry(22, "dripper", "Dripper", "逃跑魚"),
            new ItemEntry(23, "eel", "Eel", "攻擊性魚"),
            new ItemEntry(24, "flyingfish", "Flying Fish", "魚"),
            new ItemEntry(25, "footsnail", "FootSnail", "生物"),
            new ItemEntry(26, "gar", "Gar", "攻擊性魚"),
            new ItemEntry(27, "goby", "Goby", "魚"),
            new ItemEntry(28, "goldfish", "Goldfish", "魚"),
            new ItemEntry(29, "halibut", "Halibut", "魚"),
            new ItemEntry(31, "leech", "Leech", "生物"),
            new ItemEntry(32, "lobster", "Lobster", "螃蟹"),
            new ItemEntry(33, "mackerel", "Mackerel", "魚"),
            new ItemEntry(34, "needlefish", "Needlefish", "魚"),
            new ItemEntry(35, "oarfish", "Oarfish", "魚"),
            new ItemEntry(36, "parrotfish", "Parrotfish", "攻擊性魚"),
            new ItemEntry(37, "perch", "Perch", "魚"),
            new ItemEntry(38, "pike", "Pike", "魚"),
            new ItemEntry(39, "piranha", "Piranha", "攻擊性魚"),
            new ItemEntry(40, "redsnapper", "Red Snapper", "攻擊性魚"),
            new ItemEntry(41, "salmon", "Salmon", "魚"),
            new ItemEntry(42, "seaurchin", "Sea Urchin", "攻擊性魚"),
            new ItemEntry(43, "seagull", "Seagull", "鳥"),
            new ItemEntry(44, "seahorse", "Seahorse", "魚"),
            new ItemEntry(45, "sengarat", "Sengarat", "魚"),
            new ItemEntry(46, "shrimp", "Shrimp", "魚"),
            new ItemEntry(47, "stonefish", "Stonefish", "攻擊性魚"),
            new ItemEntry(48, "superdwarffish", "Superdwarf Fish", "魚"),
            new ItemEntry(49, "tigerfish", "Tigerfish", "攻擊性魚"),
            new ItemEntry(50, "triggerfish", "Triggerfish", "魚"),
            new ItemEntry(51, "voxelfish", "Voxel Fish", "魚"),
            new ItemEntry(52, "yellowboxfish", "Yellow Boxfish", "魚"),
            new ItemEntry(53, "deadplayer", "DeadPlayer", "屍體"),
            new ItemEntry(54, "assaultrifle", "Assault Rifle", "槍械"),
            new ItemEntry(55, "badball", "Badball", "道具"),
            new ItemEntry(56, "beer", "Beer", "生物"),
            new ItemEntry(57, "brassknuckles", "Brass Knuckles", "近戰"),
            new ItemEntry(58, "brassknucklespackedbackup", "BrassKnucklesPackedBackup", "近戰"),
            new ItemEntry(59, "crabfishingrod", "Crab Fishing Rod", "蟹竿"),
            new ItemEntry(60, "dynamite", "Dynamite", "爆裂物"),
            new ItemEntry(61, "fishingrod", "Fishing Rod", "魚竿"),
            new ItemEntry(62, "disc", "Disc", "飛盤"),
            new ItemEntry(63, "knife", "Knife", "近戰"),
            new ItemEntry(64, "knifepackedbackup", "KnifePackedBackup", "近戰"),
            new ItemEntry(65, "map", "Map", "地圖"),
            new ItemEntry(66, "pistol", "Pistol", "槍械"),
            new ItemEntry(67, "radio", "Radio", "收音機"),
            new ItemEntry(68, "shotgun", "Shotgun", "槍械"),
            new ItemEntry(69, "smg", "Smg", "槍械"),
            new ItemEntry(70, "sniperrifle", "Sniper Rifle", "槍械"),
            new ItemEntry(71, "snowball1", "Snowball1", "道具"),
            new ItemEntry(72, "snowball2", "Snowball2", "道具"),
            new ItemEntry(73, "snowball3", "Snowball3", "道具"),
            new ItemEntry(74, "albatrosshead", "Albatross Head", "道具"),
            new ItemEntry(75, "giantpiranhaskeleton", "GiantPiranhaSkeleton", "道具"),
            new ItemEntry(76, "pufferfishfin", "Pufferfish Fin", "道具"),
            new ItemEntry(77, "spidercrabshell", "Spidercrab Shell", "道具"),
            new ItemEntry(78, "whalefin", "Whale Fin", "道具"),
            new ItemEntry(79, "rockcrab", "RockCrab", "螃蟹"),
            new ItemEntry(80, "bingbong", "BingBong", "攻擊性魚"),
            new ItemEntry(81, "whalemeat", "WhaleMeat", "生物"),
            new ItemEntry(82, "crabmeat", "CrabMeat", "生物"),
            new ItemEntry(83, "pufferfishmeat", "PufferfishMeat", "生物"),
            new ItemEntry(84, "albatrossmeat", "AlbatrossMeat", "生物"),
            new ItemEntry(85, "piranhameat", "PiranhaMeat", "生物"),
        };
    }
}
